build:
    nodes:
        analysis:
            environment:
                node:
                    version: '12.22.8'
            dependencies:
                before:
                    - composer require --dev johnpbloch/wordpress
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]
filter:
    dependency_paths:
        - wordpress/
        - includes/eduadmin-api-client/
        - libraries/
    excluded_paths:
        - 'tests/*'
        - scripts/
        - Composer/
