name: Deploy new development / trunk version (master)
on:
  push:
    branches: master

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
          lfs: true
      - name: Get Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build source files
        shell: bash
        run: |
          yarn
          npx tsc
          yarn gulp deploy
          git config --global user.email "chga@multinet.se"
          git config --global user.name "Chris Gårdenberg"
          echo "machine github.com login itssimple password ${{ secrets.ITSSIMPLE_TOKEN }}" > ~/.netrc
          cd new_website && yarn install && GIT_USER=itssimple yarn run deploy
          cd ..
      - name: Deploy trunk to SVN
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        run: |
          $GITHUB_WORKSPACE/scripts/trunk_gh.sh
