name: Deploy new production version (production)
on:
  push:
    branches: production

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
          lfs: true
      - name: Get Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build source files
        shell: bash
        run: |
          yarn
          npx tsc
          yarn gulp deploy
      - name: Deploy trunk to SVN
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          SLACK_HOOKURL: ${{ secrets.SLACK_HOOKURL }}
        run: |
          $GITHUB_WORKSPACE/scripts/deploy_gh.sh
