name: check valid php (master)
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
          lfs: true
      - name: Get Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Build source files
        shell: bash
        run: |
          yarn
          npx tsc
          yarn gulp deploy
      - name: Check PHP
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require wp-coding-standards/wpcs
          $HOME/.composer/vendor/bin/phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          $HOME/.composer/vendor/bin/phpcs --standard=WordPress $GITHUB_WORKSPACE
      - name: Deploy trunk to SVN
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
        run: |
          $GITHUB_WORKSPACE/scripts/trunk_gh.sh
