name: check valid php (master)
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get Node 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Build source files
        shell: bash
        run: |
          yarn
          npx tsc
          yarn gulp deploy
  deploy:
    steps:
      - name: Deploy trunk to SVN
        run: chmod +x $GITHUB_WORKSPACE/scripts/trunk.sh && $GITHUB_WORKSPACE/scripts.trunk.sh
