name: Deploy new production version (production)
on:
  push:
    branches: production

concurrency:
  group: environment-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
          lfs: true
      - name: Get Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Build source files
        shell: bash
        run: |
          apt install -y subversion rsync git
          yarn
          npx tsc
          yarn gulp deploy
          git config --global user.email "chga@multinet.se"
          git config --global user.name "Chris Gårdenberg"
          echo "machine github.com login itssimple password ${{ secrets.ITSSIMPLE_TOKEN }}" > ~/.netrc
          cd new_website && yarn install && GIT_USER=itssimple yarn run deploy
          cd ..
      - name: Deploy trunk to SVN
        env:
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
          SLACK_HOOKURL: ${{ secrets.SLACK_HOOKURL }}
        run: |
          $GITHUB_WORKSPACE/scripts/deploy_gh.sh
